####################################################
# Define o n\u00edvel m\u00ednimo de log do console para permitir mensagens de debug/trace
quarkus.log.console.level=DEBUG

# Ativa o log para as suas classes
quarkus.log.category."io.github.kriolos".level=DEBUG

quarkus.log.category."io.quarkiverse.webforj".level=DEBUG
quarkus.log.category."io.quarkiverse.webforj".min-level=TRACE

# Ativa o debug profundo para o framework webforJ
quarkus.log.category."com.webforj".level=DEBUG
quarkus.log.category."com.webforj".min-level=TRACE

# Ativa o debug para o motor interno e gerenciador de licen\u00e7as
quarkus.log.category."com.basis".level=DEBUG
quarkus.log.category."com.basis".min-level=TRACE



####################################################
# Liberta o tr\u00e1fego HTTP para o Servlet interceptar sem bloqueios proativos do Quarkus
#quarkus.http.auth.proactive=true
# Garante que o Undertow permita requisi\u00e7\u00f5es an\u00f3nimas na raiz do webforJ
#quarkus.http.auth.permission.default.policy=permit


# 2. \ud83d\udee0\ufe0f RESOLU\u00c7\u00c3O DO FORBIDDEN: Desativa a valida\u00e7\u00e3o estrita de Origin do WebSocket para o Playwright
%test.quarkus.websocket.dispatch-to-virtual-thread=true
%test.quarkus.http.cors=true
%test.quarkus.http.cors.origins=*



####################################################
# WebforJ
####################################################

# DEV CONFIGURATION
webforj.entry = io.github.kriolos.opos.Application
#webforj.version=@webforj.version@
webforj.debug = true
webforj.devtools.craftforj.enabled=true
webforj.devtools.livereload.enabled=true
webforj.devtools.livereload.static-resources-enabled=true
webforj.devtools.browser.open=false




# Configura\u00e7\u00e3o base
#webforj.servlet-mapping=/*
# M\u00f3dulo de Licen\u00e7a e Seguran\u00e7a (Modo Dev)
#%dev.webforj.debug=true
#%dev.webforj.devtools.craftforj.enabled=true
#%dev.webforj.devtools.livereload.enabled = true
webforj.license.startup-timeout=0


# \ud83d\ude80 CONFIGURA\u00c7\u00c3O DE LICEN\u00c7A (Modo Produ\u00e7\u00e3o)
# Se usar um servidor de licen\u00e7as local na empresa, aponte aqui, caso contr\u00e1rio remova:
#%prod.webforj.license.server=localhost
#%prod.webforj.license.port=27000
#%prod.webforj.license.startupTimeout=5
#%prod.webforj.license.retry=1
#%prod.webforj.license.timeout=2
